import enum
from datetime import date
from sqlalchemy import String, Text, Float, Integer, Boolean, Enum as SAEnum, ForeignKey, Index, JSON, Date
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models.base import Base, TimestampMixin, UUIDPrimaryKey


class BeatStatus(str, enum.Enum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class Beat(Base, UUIDPrimaryKey, TimestampMixin):
    """Daily geo-optimized route plan per agent generated by the ML engine."""
    __tablename__ = "beats"

    agent_id: Mapped[str] = mapped_column(ForeignKey("agents.id"), nullable=False, index=True)
    beat_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    beat_number: Mapped[str] = mapped_column(String(50), unique=True, nullable=False)

    # Ordered list of case IDs in visit sequence
    ordered_case_ids: Mapped[list] = mapped_column(JSON, default=list, nullable=False)

    # Route metadata
    total_cases: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    estimated_distance_km: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    estimated_duration_minutes: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    total_target_amount: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)

    # Progress
    status: Mapped[BeatStatus] = mapped_column(
        SAEnum(BeatStatus, name="beat_status_enum"), default=BeatStatus.PLANNED, nullable=False
    )
    cases_completed: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    amount_collected: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)

    # ML metadata
    is_ml_generated: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    ml_model_version: Mapped[str | None] = mapped_column(String(50), nullable=True)
    geo_cluster_id: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Override tracking
    manually_modified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    modified_by_id: Mapped[str | None] = mapped_column(ForeignKey("users.id"), nullable=True)

    # Attendance / leave tracking — when an agent is on leave, a CANCELLED beat is
    # created so we have a daily record for every working day across 6 months.
    is_leave_day: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    leave_type: Mapped[str | None] = mapped_column(
        String(20), nullable=True
    )  # SICK_LEAVE | CASUAL_LEAVE | EARNED_LEAVE | ABSENT | None
    leave_remarks: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Link to nightly allocation run (if generated by planner)
    allocation_run_id: Mapped[str | None] = mapped_column(ForeignKey("allocation_runs.id"), nullable=True, index=True)

    agent: Mapped["Agent"] = relationship("Agent", back_populates="beats")  # type: ignore[name-defined]  # noqa: F821
    allocation_run: Mapped["AllocationRun | None"] = relationship("AllocationRun", back_populates="beats")  # type: ignore[name-defined]  # noqa: F821

    __table_args__ = (
        Index("ix_beat_agent_date", "agent_id", "beat_date", unique=True),
        Index("ix_beat_date_status", "beat_date", "status"),
    )
