# ─── CHANGELOG (standalone plan) ────────────────────────────────────────────
# 2026-09-24 (B08) — planning.beats (docs/DATA-MODEL-V2.md §4.5): tenant
#   columns with composite FKs; beat_number unique per agency (employee codes
#   are); money columns NUMERIC; allocation_run_id is a proper UUID FK (it was
#   VARCHAR(36) from raw DDL outside Alembic).
#   DEFERRED to B23: ordered_case_ids / route_legs → planning.beat_stops (58
#   references in 17 files move with it) and the leave columns → attendance.
#   Creating those tables before their readers move would be two sources.
# ────────────────────────────────────────────────────────────────────────────
import enum
from datetime import date
from sqlalchemy import (
    Boolean, Date, Enum as SAEnum, Float, ForeignKeyConstraint, Index, Integer, SmallInteger, String, Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models.base import PUBLIC, Base, JsonDoc, Money, TimestampMixin, UUIDPrimaryKey, UUIDType, uuid_fk


class BeatStatus(str, enum.Enum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


BEAT_STATUS_SQL = SAEnum(BeatStatus, name="beat_status_enum", schema=PUBLIC, metadata=Base.metadata)


class Beat(Base, UUIDPrimaryKey, TimestampMixin):
    """Daily geo-optimized route plan per agent generated by the ML engine."""
    __tablename__ = "beats"
    __tenant_parents__ = (("agent_id", "Agent"),)

    bank_id: Mapped[str] = mapped_column(UUIDType, nullable=False)
    agency_id: Mapped[str] = mapped_column(UUIDType, nullable=False)
    agent_id: Mapped[str] = mapped_column(UUIDType, nullable=False)
    beat_date: Mapped[date] = mapped_column(Date, nullable=False)
    beat_number: Mapped[str] = mapped_column(String(50), nullable=False)

    # Ordered list of case IDs in visit sequence (→ beat_stops in B23)
    ordered_case_ids: Mapped[list] = mapped_column(JsonDoc, default=list, nullable=False)

    # Route metadata
    total_cases: Mapped[int] = mapped_column(SmallInteger, default=0, nullable=False)
    estimated_distance_km: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    estimated_duration_minutes: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    total_target_amount: Mapped[float] = mapped_column(Money, default=0.0, nullable=False)

    # Progress
    status: Mapped[BeatStatus] = mapped_column(BEAT_STATUS_SQL, default=BeatStatus.PLANNED, nullable=False)
    cases_completed: Mapped[int] = mapped_column(SmallInteger, default=0, nullable=False)
    amount_collected: Mapped[float] = mapped_column(Money, default=0.0, nullable=False)

    # ── Route detail, from the optimiser that produced it (2026-09-08) ──────
    # WHY THESE EXIST. estimated_distance_km and estimated_duration_minutes above
    # were computed by planner_service as Haversine x 1.15 and km/25 + 20 min a
    # stop, AFTER core/routing had already fetched a real OSRM road matrix and
    # thrown it away. So the ETA an agent saw was crow-flies even on nights OSRM
    # answered perfectly. These columns hold what the solver actually produced.
    #
    # route_source is the honest bit: "osrm" or "haversine". The fallback used to
    # be silent, so nobody could tell how often the demo server was answering.
    route_geometry: Mapped[str | None] = mapped_column(Text)
    route_legs: Mapped[list | None] = mapped_column(JsonDoc)
    route_source: Mapped[str | None] = mapped_column(String(20))

    # ── Plan versus reality ─────────────────────────────────────────────────
    # A Beat recorded an estimate and NOTHING to compare it against, so no
    # routing change could ever be shown to have improved anything, and there
    # was no label for a travel-time model. Filled by the nightly reconciliation
    # from AgentLocation fixes and visit check-in/check-out times.
    actual_distance_km: Mapped[float | None] = mapped_column(Float)
    actual_duration_minutes: Mapped[int | None] = mapped_column(Integer)

    # ML metadata
    is_ml_generated: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    ml_model_version: Mapped[str | None] = mapped_column(String(50))
    geo_cluster_id: Mapped[int | None] = mapped_column(Integer)

    # Override tracking
    manually_modified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    modified_by_id: Mapped[str | None] = uuid_fk("tenancy.users.id", nullable=True)

    # Attendance / leave tracking — when an agent is on leave, a CANCELLED beat is
    # created so we have a daily record for every working day across 6 months.
    # (→ workforce.attendance in B23)
    is_leave_day: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    leave_type: Mapped[str | None] = mapped_column(
        String(20)
    )  # SICK_LEAVE | CASUAL_LEAVE | EARNED_LEAVE | ABSENT | None
    leave_remarks: Mapped[str | None] = mapped_column(Text)

    # Link to nightly allocation run (if generated by planner)
    allocation_run_id: Mapped[str | None] = mapped_column(UUIDType)

    agent: Mapped["Agent"] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "Agent", back_populates="beats", primaryjoin="Beat.agent_id == Agent.id", foreign_keys=[agent_id])
    allocation_run: Mapped["AllocationRun | None"] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "AllocationRun", back_populates="beats", primaryjoin="Beat.allocation_run_id == AllocationRun.id",
        foreign_keys=[allocation_run_id])

    __table_args__ = (
        UniqueConstraint("agency_id", "beat_number"),
        UniqueConstraint("id", "agency_id"),
        ForeignKeyConstraint(["agent_id", "agency_id"], ["workforce.agents.id", "workforce.agents.agency_id"],
                             ondelete="RESTRICT"),
        ForeignKeyConstraint(["allocation_run_id", "agency_id"],
                             ["planning.allocation_runs.id", "planning.allocation_runs.agency_id"],
                             ondelete="RESTRICT"),
        # Name kept: planner_service quotes it to recognise the concurrent-plan
        # collision (the 409 CLAUDE.md documents).
        Index("ix_beat_agent_date", "agent_id", "beat_date", unique=True),
        Index("ix_beat_date_status", "agency_id", "beat_date", "status"),
        Index(None, "allocation_run_id"),
        {"schema": "planning"},
    )
