"""Shadow-run the allocator with the trained recovery_risk model, and diff.

    python -m scripts.shadow_allocation_ml
    python -m scripts.shadow_allocation_ml --cases 400 --agents 18 --seed 7

READ-ONLY, AND IT CHANGES NOTHING. It builds two plans over the same book — one
exactly as production runs today, one where `prob_recovery` is informed by the
model — and reports the difference. Nothing is written to any database, no
setting is flipped, and `ML_SCORING_ENABLED` is not consulted at all.

WHAT IS ACTUALLY BEING SWAPPED, because the obvious reading is wrong.
`affinity_score` is NOT replaced. It is an AGENT-side estimate (what share this
agent recovers on work of this kind) and the model is a BORROWER-side one (will
this borrower pay). Substituting one for the other would make every agent score
identically on a case and destroy the differentiation the allocator exists for.

The swap is inside `prob_recovery`, which today is clamp(agent_skill x tier) and
carries no borrower-side input at all:

    current   prob = clamp( shrunk_win            x tier_uplift , 0.20, 0.85 )
    shadow    prob = clamp( P(pay) x eb_multiplier x tier_uplift , 0.20, 0.85 )

`eb_multiplier` is by construction a ratio centred on 1.0 (shrunk_win divided by
the segment prior, bounded to [0.75, 1.25]), so this is a calibrated base rate
modulated by a bounded relative agent effect — not two estimates of one quantity
multiplied together, which is the 2026-09-03 defect this deliberately avoids.

THE BOOK. This environment has no reachable database, so the comparison runs on
an in-memory book generated by app/ml/simulation/book_simulator.py — the same
generator the model was trained on, at a different seed so the accounts are not
the training rows. That is a real limitation and it is stated in the output: the
numbers below describe the model's EFFECT ON THE ALLOCATOR, which is a property
of the two scoring formulas, not a claim about live borrowers. Point
DATABASE_URL at the demo book and pass --from-db to run the identical comparison
there.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND))

import numpy as np  # noqa: E402

from app.ml.pipeline.engine import DecisionEngine  # noqa: E402
from app.ml.simulation.book_simulator import BookSimulator, SimConfig  # noqa: E402
from app.models.agent import Agent, AgentSpecialization, AgentTier  # noqa: E402
from app.models.allocation_decision import AllocationOutcome  # noqa: E402
from app.models.case import Case  # noqa: E402
from app.models.customer import Customer  # noqa: E402
from app.models.loan import DPDBucket, Loan, LoanType  # noqa: E402
from app.services.global_allocator import GlobalAllocator  # noqa: E402

NCR = [(28.6139, 77.2090), (28.5355, 77.3910), (28.4595, 77.0266),
       (28.4089, 77.3178), (28.6692, 77.4538)]
LANGS = ["HINDI", "ENGLISH", "PUNJABI", "URDU", "HARYANVI"]


# ---------------------------------------------------------------------------
# Book construction — transient ORM objects, never added to a session
# ---------------------------------------------------------------------------

def build_book(n_cases: int, n_agents: int, seed: int):
    """A realistic pool of cases and agents, from the simulator's own panel.

    Objects are constructed but never persisted. GlobalAllocator.allocate() only
    reads attributes off them, so a session is not needed — which is what makes
    this comparison runnable with no infrastructure at all.
    """
    rng = np.random.default_rng(seed)
    cfg = SimConfig(n_borrowers=max(n_cases, 500), months=6, seed=seed)
    panel = BookSimulator(cfg).run()
    latest = panel[panel.month_index == panel.month_index.max()].head(n_cases)

    agents: list[Agent] = []
    for i in range(n_agents):
        lat, lon = NCR[i % len(NCR)]
        ag = Agent()
        ag.id = f"AG{i:03d}"
        ag.employee_code = f"EMP{i:03d}"
        ag.base_latitude = lat + float(rng.normal(0, 0.02))
        ag.base_longitude = lon + float(rng.normal(0, 0.02))
        ag.max_cases_per_day = int(rng.integers(10, 16))
        ag.tier = [AgentTier.TIER_1, AgentTier.TIER_2, AgentTier.TIER_3][i % 3]
        ag.specialization = [AgentSpecialization.SECURED, AgentSpecialization.UNSECURED,
                             AgentSpecialization.BOTH][i % 3]
        ag.languages_spoken = list(rng.choice(LANGS, 2, replace=False))
        ag.gender = "F" if i % 4 == 0 else "M"
        agents.append(ag)

    cases: list[Case] = []
    features: dict[str, dict] = {}
    truth: dict[str, float] = {}
    for k, (_, row) in enumerate(latest.iterrows()):
        lat, lon = NCR[k % len(NCR)]
        cust = Customer()
        cust.id = f"C{k:05d}"
        cust.latitude = lat + float(rng.normal(0, 0.05))
        cust.longitude = lon + float(rng.normal(0, 0.05))
        cust.language_preference = str(rng.choice(LANGS))
        cust.city = row["city"]
        cust.cibil_score = None if np.isnan(row["cibil_score"]) else int(row["cibil_score"])
        # The three hard gates that must remain untouched by any scoring change.
        cust.do_not_contact = bool(rng.random() < 0.03)
        cust.is_hostile = bool(rng.random() < 0.02)
        cust.requires_female_agent = bool(rng.random() < 0.06)

        loan = Loan()
        loan.id = f"L{k:05d}"
        loan.loan_type = LoanType[row["loan_type"]]
        loan.dpd = int(row["dpd"])
        loan.dpd_bucket = DPDBucket[row["dpd_bucket"]]
        loan.emi_amount = float(row["emi_amount"])
        loan.overdue_amount = float(row["overdue_amount"])
        loan.total_outstanding = float(row["total_outstanding"])

        c = Case()
        c.id = f"CASE{k:05d}"
        c.case_number = f"CASE-{k:05d}"
        c.customer_id = cust.id
        c.loan_id = loan.id
        c.customer = cust
        c.loan = loan
        c.target_amount = float(row["overdue_amount"])
        c.collected_amount = float(rng.uniform(0, 0.25) * row["overdue_amount"])
        # A third of the pool is already held by someone, so the continuity term
        # is exercised rather than being uniformly zero.
        c.agent_id = agents[int(rng.integers(0, n_agents))].id if rng.random() < 0.33 else None
        cases.append(c)

        # The realised next-cycle outcome for THIS account, from the simulator.
        # It is never shown to the allocator or the model — it exists only so
        # both forecasts can be scored against what actually happened.
        truth[c.id] = 1.0 - float(row["y"])

        features[c.id] = {
            "dpd": float(row["dpd"]),
            "cibil_score": (None if np.isnan(row["cibil_score"])
                            else float(row["cibil_score"])),
            "ptp_kept_ratio": float(row["ptp_kept_ratio"]),
            "overdue_amount": float(row["overdue_amount"]),
        }

    return cases, agents, features, truth


# ---------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------

def summarise(decisions):
    allocated, blocked, deferred = {}, set(), set()
    for d in decisions:
        if d.outcome == AllocationOutcome.ALLOCATED.value:
            allocated[d.case_id] = d.allocated_agent_id
        elif d.outcome == AllocationOutcome.BLOCKED.value:
            blocked.add(d.case_id)
        else:
            deferred.add(d.case_id)
    return allocated, blocked, deferred


def run(n_cases: int, n_agents: int, seed: int, objective: str) -> dict:
    engine = DecisionEngine.get("recovery_risk")
    if engine is None:
        raise SystemExit(
            "no champion recovery_risk artifact. Train one first:\n"
            "  python -m scripts.train_models --model recovery_risk")

    cases, agents, features, truth = build_book(n_cases, n_agents, seed)
    prio = {c.id: 50.0 for c in cases}

    # P(no material payment) -> P(material payment). The model predicts the RISK
    # event (see ml/pipeline/config.py); the allocator wants the complement.
    probs_bad = engine.score_batch([features[c.id] for c in cases])
    p_recover = {c.id: (1.0 - p) for c, p in zip(cases, probs_bad) if p is not None}
    print(f"  scored {len(p_recover)} of {len(cases)} cases with "
          f"{engine.model} v{engine.version}")

    def allocate(use_ml: bool):
        alloc = GlobalAllocator(objective=objective,
                                ml_recovery_probability=p_recover,
                                use_ml_affinity=use_ml)
        by_agent, decisions, expected = alloc.allocate(
            cases=cases, agents=agents, history_matrix={}, prio_scores=prio)
        # Reset the mutation allocate() performs on its inputs so the second run
        # sees the same starting book as the first. Without this the continuity
        # term would read run A's assignments as run B's incumbents and the diff
        # would measure the reset, not the model.
        return by_agent, decisions, expected

    collectable = {c.id: max(0.0, float(c.target_amount or 0.0)
                             - float(c.collected_amount or 0.0)) for c in cases}
    incumbent = {c.id: c.agent_id for c in cases}
    base_by_agent, base_dec, base_exp = allocate(use_ml=False)
    for c in cases:
        c.agent_id = incumbent[c.id]
    ml_by_agent, ml_dec, ml_exp = allocate(use_ml=True)
    for c in cases:
        c.agent_id = incumbent[c.id]

    base_alloc, base_blocked, base_def = summarise(base_dec)
    ml_alloc, ml_blocked, ml_def = summarise(ml_dec)

    common = set(base_alloc) & set(ml_alloc)
    moved = sorted(cid for cid in common if base_alloc[cid] != ml_alloc[cid])

    # Distribution of the two probabilities, over pairs the solver actually chose.
    def probs(decisions, key):
        return [d.score_breakdown.get(key) for d in decisions
                if d.outcome == AllocationOutcome.ALLOCATED.value
                and d.score_breakdown.get(key) is not None]

    cur_p = probs(base_dec, "prob_recovery")
    ml_p = probs(base_dec, "prob_recovery_ml")

    # ── Calibration: is either forecast right? ─────────────────────────────
    # THE DECISIVE NUMBER. A large swing in "expected recovery" is meaningless
    # on its own — it says the two formulas disagree, not which is closer to the
    # truth. Both are scored here against the realised recovery rate on the
    # exact accounts the plan allocated.
    # Brier over the whole pool, on the probabilities each formula assigns —
    # the proper scoring rule. A mean-vs-mean calibration gap can be zero while
    # every individual probability is wrong; Brier cannot.
    all_bd = {d.case_id: d.score_breakdown for d in base_dec
              if d.score_breakdown.get("prob_recovery") is not None}
    brier_ids = [cid for cid in all_bd if cid in truth]
    y_true = np.array([truth[cid] for cid in brier_ids])
    p_cur = np.array([all_bd[cid]["prob_recovery"] for cid in brier_ids])
    p_ml = np.array([all_bd[cid]["prob_recovery_ml"] if
                     all_bd[cid]["prob_recovery_ml"] is not None
                     else all_bd[cid]["prob_recovery"] for cid in brier_ids])
    brier = {
        "n": len(brier_ids),
        "current": round(float(np.mean((p_cur - y_true) ** 2)), 5),
        "ml": round(float(np.mean((p_ml - y_true) ** 2)), 5),
    }
    brier["improvement_pct"] = round(
        100.0 * (brier["current"] - brier["ml"]) / brier["current"], 1) if brier["current"] else None

    # Reliability of each formula, five bands, over the same pool.
    def reliability(pred):
        import pandas as pd
        d = pd.DataFrame({"p": pred, "y": y_true})
        try:
            d["band"] = pd.qcut(d.p, 5, labels=False, duplicates="drop") + 1
        except ValueError:
            return []
        g = d.groupby("band").agg(n=("y", "size"), predicted=("p", "mean"),
                                  actual=("y", "mean")).reset_index()
        g["gap"] = g.predicted - g.actual
        return [{k: (round(float(v), 4) if k != "n" and k != "band" else int(v))
                 for k, v in row.items()} for row in g.to_dict("records")]

    # OOT figures, read back from the artifact rather than recomputed, so the
    # shadow report cannot quote a number the shipped model does not carry.
    oot = (engine.metadata.get("metrics") or {}).get("oot") or {}
    oot_summary = {
        "gini": oot.get("gini"), "ks": oot.get("ks"),
        "bad_rate": oot.get("bad_rate"), "n": oot.get("n"),
        "gate_summary": engine.metadata.get("gate_summary"),
        "bootstrap_ci": engine.metadata.get("bootstrap_gini_oot", {}),
    }

    alloc_ids = [cid for cid in base_alloc if cid in truth]
    realised = float(np.mean([truth[cid] for cid in alloc_ids])) if alloc_ids else None
    bd = {d.case_id: d.score_breakdown for d in base_dec
          if d.outcome == AllocationOutcome.ALLOCATED.value}
    cur_mean = float(np.mean([bd[c]["prob_recovery"] for c in alloc_ids
                              if bd.get(c, {}).get("prob_recovery") is not None]))
    ml_mean = float(np.mean([bd[c]["prob_recovery_ml"] for c in alloc_ids
                             if bd.get(c, {}).get("prob_recovery_ml") is not None]))

    # PLAN QUALITY — the question the promote decision actually turns on.
    # "Assignments moved" counts only cases allocated in BOTH plans; cases that
    # swap in and out of the day are a separate and larger effect, and they are
    # where a value-based re-forecast does its real work. So both plans are
    # scored on what their chosen set actually recovered.
    def plan_quality(alloc):
        ids = [cid for cid in alloc if cid in truth]
        if not ids:
            return None
        rate = float(np.mean([truth[cid] for cid in ids]))
        rupees = float(sum(collectable[cid] * truth[cid] for cid in ids))
        return {"cases": len(ids),
                "realised_recovery_rate": round(rate, 4),
                "realised_recovered_inr": round(rupees, 0)}

    swapped_in = sorted(set(ml_alloc) - set(base_alloc))
    swapped_out = sorted(set(base_alloc) - set(ml_alloc))
    quality = {
        "base": plan_quality(base_alloc),
        "ml": plan_quality(ml_alloc),
        "swapped_in": len(swapped_in),
        "swapped_out": len(swapped_out),
        "swapped_in_realised_rate": round(float(np.mean(
            [truth[c] for c in swapped_in if c in truth])), 4) if swapped_in else None,
        "swapped_out_realised_rate": round(float(np.mean(
            [truth[c] for c in swapped_out if c in truth])), 4) if swapped_out else None,
    }

    return {
        "plan_quality": quality,
        "brier": brier,
        "reliability_current": reliability(p_cur),
        "reliability_ml": reliability(p_ml),
        "oot": oot_summary,
        "deferred_identical": base_def == ml_def,
        "deferred_base": len(base_def),
        "deferred_ml": len(ml_def),
        "deferred_symmetric_difference": len(base_def ^ ml_def),
        "calibration": {
            "n_allocated_with_outcome": len(alloc_ids),
            "realised_recovery_rate": round(realised, 4) if realised else None,
            "forecast_current": round(cur_mean, 4),
            "forecast_ml": round(ml_mean, 4),
            "error_current": round(cur_mean - realised, 4) if realised else None,
            "error_ml": round(ml_mean - realised, 4) if realised else None,
            "relative_error_current_pct": round(100 * (cur_mean - realised) / realised, 1)
            if realised else None,
            "relative_error_ml_pct": round(100 * (ml_mean - realised) / realised, 1)
            if realised else None,
        },
        "objective": objective,
        "model": f"{engine.model} v{engine.version}",
        "cases": len(cases),
        "agents": len(agents),
        "scored": len(p_recover),
        "base": {"allocated": len(base_alloc), "blocked": len(base_blocked),
                 "deferred": len(base_def), "expected_recovery": round(base_exp, 2)},
        "ml": {"allocated": len(ml_alloc), "blocked": len(ml_blocked),
               "deferred": len(ml_def), "expected_recovery": round(ml_exp, 2)},
        "assignments_moved": len(moved),
        "assignments_compared": len(common),
        "pct_moved": round(100.0 * len(moved) / max(len(common), 1), 2),
        "expected_recovery_delta_pct": round(
            100.0 * (ml_exp - base_exp) / base_exp, 2) if base_exp else None,
        "blocked_identical": base_blocked == ml_blocked,
        "blocked_base": len(base_blocked),
        "blocked_ml": len(ml_blocked),
        "blocked_symmetric_difference": sorted(base_blocked ^ ml_blocked),
        "prob_recovery_current": {
            "n": len(cur_p), "mean": round(float(np.mean(cur_p)), 4),
            "std": round(float(np.std(cur_p)), 4),
            "min": round(float(np.min(cur_p)), 4),
            "max": round(float(np.max(cur_p)), 4)} if cur_p else None,
        "prob_recovery_ml": {
            "n": len(ml_p), "mean": round(float(np.mean(ml_p)), 4),
            "std": round(float(np.std(ml_p)), 4),
            "min": round(float(np.min(ml_p)), 4),
            "max": round(float(np.max(ml_p)), 4)} if ml_p else None,
        "moved_sample": moved[:10],
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cases", type=int, default=350)
    ap.add_argument("--agents", type=int, default=18)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--objective", default="BALANCED")
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args()

    print("=" * 78)
    print("  SHADOW: recovery_risk into the allocator — nothing is changed")
    print("=" * 78)
    r = run(a.cases, a.agents, a.seed, a.objective)

    if a.json:
        print(json.dumps(r, indent=2))
        return 0

    b, m = r["base"], r["ml"]
    print(f"\n  book        {r['cases']} cases / {r['agents']} agents / "
          f"objective {r['objective']}")
    print(f"  model       {r['model']}, scored {r['scored']} cases\n")

    print(f"  {'':<24}{'CURRENT':>14}{'ML-INFORMED':>14}")
    print(f"  {'-'*52}")
    print(f"  {'allocated':<24}{b['allocated']:>14}{m['allocated']:>14}")
    print(f"  {'blocked (hard gates)':<24}{b['blocked']:>14}{m['blocked']:>14}")
    print(f"  {'deferred':<24}{b['deferred']:>14}{m['deferred']:>14}")
    print(f"  {'expected recovery':<24}{b['expected_recovery']:>14,.0f}"
          f"{m['expected_recovery']:>14,.0f}")

    cur, mlp = r["prob_recovery_current"], r["prob_recovery_ml"]
    if cur and mlp:
        print(f"\n  prob_recovery over the pairs the solver chose:")
        print(f"  {'':<24}{'CURRENT':>14}{'ML-INFORMED':>14}")
        print(f"  {'-'*52}")
        for k in ("mean", "std", "min", "max"):
            print(f"  {k:<24}{cur[k]:>14.4f}{mlp[k]:>14.4f}")
        if cur["std"] < 1e-6:
            print("\n  NOTE: the current probability has ZERO spread — every "
                  "chosen pair\n        carries the same agent-skill estimate, "
                  "which is what the\n        297-of-315 sparse-EB-cell finding "
                  "predicts.")

    cal = r["calibration"]
    if cal["realised_recovery_rate"] is not None:
        print(f"\n  CALIBRATION against the realised outcome on the "
              f"{cal['n_allocated_with_outcome']} allocated cases:")
        print(f"  {'-'*52}")
        print(f"  {'actually recovered':<24}{cal['realised_recovery_rate']:>14.4f}")
        print(f"  {'forecast, current':<24}{cal['forecast_current']:>14.4f}"
              f"   ({cal['relative_error_current_pct']:+.1f}%)")
        print(f"  {'forecast, ML-informed':<24}{cal['forecast_ml']:>14.4f}"
              f"   ({cal['relative_error_ml_pct']:+.1f}%)")

    b2 = r["brier"]
    print(f"\n  BRIER over all {b2['n']} scored cases (lower is better):")
    print(f"  {'-'*52}")
    print(f"  {'current':<24}{b2['current']:>14.5f}")
    print(f"  {'ML-informed':<24}{b2['ml']:>14.5f}"
          f"   ({b2['improvement_pct']:+.1f}% better)")

    for label, rows in (("current", r["reliability_current"]),
                        ("ML-informed", r["reliability_ml"])):
        if not rows:
            continue
        print(f"\n  RELIABILITY — {label}, ascending by predicted probability:")
        print(f"  {'band':<6}{'n':>6}{'predicted':>12}{'actual':>10}{'gap':>10}")
        print(f"  {'-'*44}")
        for row in rows:
            print(f"  {row['band']:<6}{row['n']:>6}{row['predicted']:>12.4f}"
                  f"{row['actual']:>10.4f}{row['gap']:>+10.4f}")
        if len(rows) < 5:
            print(f"  only {len(rows)} distinct bands — this formula has too "
                  f"little spread to cut into five")

    o = r["oot"]
    if o.get("gini") is not None:
        ci = o.get("bootstrap_ci") or {}
        print(f"\n  OUT-OF-TIME (from the artifact, not recomputed):")
        print(f"    Gini {o['gini']}  KS {o['ks']}  bad rate {o['bad_rate']}  "
              f"n {o['n']:,}  gates {o['gate_summary']}")
        if ci.get("ci_lower_2.5") is not None:
            print(f"    bootstrap 95% CI [{ci['ci_lower_2.5']}, {ci['ci_upper_97.5']}]")

    q = r["plan_quality"]
    if q and q["base"] and q["ml"]:
        print(f"\n  PLAN QUALITY — what each plan's chosen cases actually recovered:")
        print(f"  {'':<24}{'CURRENT':>14}{'ML-INFORMED':>14}")
        print(f"  {'-'*52}")
        print(f"  {'cases in plan':<24}{q['base']['cases']:>14}{q['ml']['cases']:>14}")
        print(f"  {'realised recovery rate':<24}"
              f"{q['base']['realised_recovery_rate']:>14.4f}"
              f"{q['ml']['realised_recovery_rate']:>14.4f}")
        print(f"  {'realised recovered INR':<24}"
              f"{q['base']['realised_recovered_inr']:>14,.0f}"
              f"{q['ml']['realised_recovered_inr']:>14,.0f}")
        if q["swapped_in"]:
            print(f"\n  {q['swapped_out']} cases dropped from the plan, "
                  f"{q['swapped_in']} added.")
            print(f"    dropped cases actually recovered at "
                  f"{q['swapped_out_realised_rate']:.4f}")
            print(f"    added   cases actually recovered at "
                  f"{q['swapped_in_realised_rate']:.4f}")

    print(f"\n  assignments moved        {r['assignments_moved']} of "
          f"{r['assignments_compared']}  ({r['pct_moved']}%)")
    print(f"  expected recovery delta  {r['expected_recovery_delta_pct']:+.2f}%"
          f"   <- a RE-FORECAST, not a loss; see calibration above"
          if abs(cal.get("error_ml") or 1) < abs(cal.get("error_current") or 0)
          else f"  expected recovery delta  {r['expected_recovery_delta_pct']:+.2f}%")
    ok = r["blocked_identical"]
    print(f"  BLOCKED set identical    {'YES' if ok else 'NO'}  "
          f"({r['blocked_base']} vs {r['blocked_ml']})"
          f"{'' if ok else '  <-- SAFETY PROPERTY VIOLATED'}")
    dok = r["deferred_identical"]
    print(f"  DEFERRED set identical   {'YES' if dok else 'NO'}  "
          f"({r['deferred_base']} vs {r['deferred_ml']}, "
          f"{r['deferred_symmetric_difference']} differ)")

    print("\n  " + "-" * 74)
    if not ok:
        print("  STOP. A scoring change that moves the BLOCKED set is a "
              "COMPLIANCE change,\n  not a scoring change. Do not promote.")
    else:
        print("  The hard gates did not move: DNC, hostility, the female-agent\n"
              "  requirement, the territory radius and PTP fatigue all run "
              "BEFORE scoring,\n  so no change to prob_recovery can reach them. "
              "That is the safety property,\n  and it holds by construction — "
              "this run is the evidence, not the reason.")
    print("\n  SYNTHETIC BOOK. These figures describe the model's effect on the\n"
          "  ALLOCATOR's arithmetic. They are not evidence about real borrowers.")
    return 0 if r["blocked_identical"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
