"""Turn alembic's raw autogenerate of the v2 tables into v2_0002 (task B11).

    python -m scripts.dev.alembic_v2_postprocess alembic/raw/v2_0002_tables.autogen.txt \
        alembic/versions/v2_0002_tables.py

Committed with its input (alembic/raw/v2_0002_tables.autogen.txt) so the
baseline can be reviewed, re-run and shown deterministic:
tests/test_alembic_v2_baseline.py re-applies `postprocess` to the raw file
and requires the result to equal v2_0002 byte for byte (coordinator audit
MED 5, 2026-09-24).

The rules, and why each exists:
1. sa.Enum(..., name=X, schema='public', metadata=MetaData()) ->
   postgresql.ENUM(name=X, schema='public', create_type=False): v2_0001
   creates the types; op.create_table would try to CREATE them again.
2. JSON().with_variant(JSONB) -> postgresql.JSONB: the revision is
   Postgres-only.
3. Every surrogate `id` gets server_default gen_random_uuid() (design §2.1).
4. use_alter FKs are pulled out of CREATE TABLE — SQLAlchemy omits them
   there and alembic never emits them, so left inline they would silently
   never exist — and added with op.create_foreign_key after every table.
5. The five partitioned parents get their composite PK and PARTITION BY
   (design §7.1); v2_0003 creates the partitions.
6. alembic_version is not ours to drop.
"""
from __future__ import annotations

import ast
import pathlib
import re
import sys

PARTITIONED = {
    # table: (pk columns, partition clause)
    "model_predictions": (("id", "as_of_date"), "RANGE (as_of_date)"),
    "allocation_decisions": (("id", "plan_date"), "RANGE (plan_date)"),
    "audit_logs": (("id", "created_at"), "RANGE (created_at)"),
    "agent_locations": (("id", "is_sos", "recorded_at"), "LIST (is_sos)"),
    "loan_dpd_history": (("loan_id", "as_of_date"), "RANGE (as_of_date)"),
}

HEADER = '''"""v2 baseline, step 2 of 8: every table, from the models (task B11).

Autogenerated against an empty database at v2_0001, then post-processed by
scripts/dev/alembic_v2_postprocess.py from alembic/raw/v2_0002_tables.autogen.txt
(tests/test_alembic_v2_baseline.py re-derives this file from the two and
requires an exact match). The rules, restated so this file stands alone:
  - enum columns reference the types v2_0001 created (create_type=False);
  - JSON is JSONB; every surrogate `id` defaults to gen_random_uuid();
  - use_alter FKs (the agency<->user, contract->document, cases<->bank_actions
    and predictions->cases cycles) are added at the end with
    op.create_foreign_key — left inline, SQLAlchemy omits them from CREATE
    TABLE and nothing else would ever create them;
  - the five partitioned parents (design §7.1) carry their composite PK and
    PARTITION BY here; v2_0003 creates their partitions. The ORM keeps `id`
    as its identity (§7.2), so the models declare the id-only PK.

Revision ID: v2_0002
Revises: v2_0001
Create Date: 2026-09-24
"""
'''


class PostprocessError(ValueError):
    pass


def postprocess(src: str) -> str:
    up_start = src.index("def upgrade() -> None:")
    down_start = src.index("def downgrade() -> None:")
    up, down = src[up_start:down_start], src[down_start:]

    up = re.sub(r"    op\.drop_table\('alembic_version'\)\n", "", up)
    down = re.sub(r"    op\.create_table\('alembic_version',.*?\n    \)\n", "", down, flags=re.S)

    alter_fks = []
    out_blocks = []
    for b in re.split(r"(?=    op\.create_table\()", up):
        m = re.match(r"    op\.create_table\('(\w+)',", b)
        if not m:
            out_blocks.append(b)
            continue
        table = m.group(1)
        sm = re.search(r"schema='(\w+)'\n    \)", b)
        schema = sm.group(1) if sm else None
        kept = []
        for ln in b.split("\n"):
            fk = re.match(r"\s*sa\.ForeignKeyConstraint\((\[[^\]]*\]), (\[[^\]]*\]), name=op\.f\('(\w+)'\)(.*)\),?\s*$",
                          ln)
            if fk and "use_alter=True" in fk.group(4):
                local, remote, name, rest = fk.groups()
                od = re.search(r"ondelete='([\w ]+)'", rest)
                im = re.search(r"initially='(\w+)'", rest)
                remote_cols = ast.literal_eval(remote)
                ref_schema, ref_table = remote_cols[0].split(".")[:2]
                alter_fks.append(dict(
                    name=name, table=table, schema=schema, ref_table=ref_table, ref_schema=ref_schema,
                    local=ast.literal_eval(local), ref_cols=[c.split(".")[2] for c in remote_cols],
                    ondelete=od.group(1) if od else None, deferrable="deferrable=True" in rest,
                    initially=im.group(1) if im else None))
                continue
            kept.append(ln)
        b = "\n".join(kept)
        if table in PARTITIONED:
            pk, clause = PARTITIONED[table]
            new_pk = f"sa.PrimaryKeyConstraint({', '.join(repr(c) for c in pk)}, name=op.f('pk_{table}'))"
            b, n = re.subn(r"sa\.PrimaryKeyConstraint\([^)]*name=op\.f\('pk_" + table + r"'\)\)", new_pk, b)
            if n != 1:
                raise PostprocessError(f"PK not found for {table}")
            b = b.replace(f"schema='{schema}'\n    )", f"schema='{schema}',\n    postgresql_partition_by='{clause}'\n    )", 1)
        out_blocks.append(b)
    up = "".join(out_blocks)

    up = re.sub(r"sa\.Enum\((?:'[^']*', )*name='(\w+)', schema='public', metadata=MetaData\(\)\)",
                r"postgresql.ENUM(name='\1', schema='public', create_type=False)", up)
    if "sa.Enum(" in up:
        raise PostprocessError("an sa.Enum was not rewritten")
    up = up.replace("sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql')",
                    "postgresql.JSONB(astext_type=sa.Text())")
    up = up.replace("sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),",
                    "sa.Column('id', sa.Uuid(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),")

    end_marker = "    # ### end Alembic commands ###"
    fk_ops = ["    # use_alter FKs (cycles), added once every table exists."]
    drop_ops = []
    for fk in alter_fks:
        extra = f", ondelete={fk['ondelete']!r}" if fk["ondelete"] else ""
        extra += ", deferrable=True" if fk["deferrable"] else ""
        extra += f", initially={fk['initially']!r}" if fk["initially"] else ""
        fk_ops.append(f"    op.create_foreign_key({fk['name']!r}, {fk['table']!r}, {fk['ref_table']!r}, {fk['local']!r}, "
                      f"{fk['ref_cols']!r}, source_schema={fk['schema']!r}, referent_schema={fk['ref_schema']!r}{extra})")
        drop_ops.append(f"    op.drop_constraint({fk['name']!r}, {fk['table']!r}, schema={fk['schema']!r}, type_='foreignkey')")
    up = up.replace(end_marker, "\n".join(fk_ops) + "\n" + end_marker, 1)
    down = down.replace("    # ### commands auto generated by Alembic - please adjust! ###\n",
                        "    # ### commands auto generated by Alembic - please adjust! ###\n" + "\n".join(drop_ops) + "\n", 1)

    body = src[:up_start]
    body = body[body.index("from typing"):]
    return HEADER + body + up + down


def main(argv: list[str]) -> int:
    raw, out = pathlib.Path(argv[0]), pathlib.Path(argv[1])
    out.write_text(postprocess(raw.read_text(encoding="utf-8")), encoding="utf-8", newline="\n")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
