"""baseline schema

Revision ID: d7a84c5a710f
Revises: 
Create Date: 2026-07-14 17:20:06.940610

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd7a84c5a710f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
