"""add used_quick_login_tokens table

Revision ID: cfb13e480d4c
Revises: d7a84c5a710f
Create Date: 2026-07-15 17:19:46.386765

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cfb13e480d4c'
down_revision: Union[str, None] = 'd7a84c5a710f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_quick_login_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_quick_login_tokens')
    # ### end Alembic commands ###
