# ─── CHANGELOG (prototype → product) ─────────────────────────────────────────
# 2026-08-19 — New file. Six product features called an LLM directly, each with
#   its own inline client, its own hardcoded model="gpt-4o-mini", and its own
#   `except Exception: pass`. With OPENAI_API_KEY empty every one of them
#   quietly served a written-in answer instead, and nothing anywhere recorded
#   that it had. A missing key, an expired subscription, a rate limit and a
#   malformed reply were indistinguishable from the outside — they all looked
#   like the feature working normally.
#
#   This is the single seam they now share. Deliberately the same shape as
#   core/transcription.py, which already does provider selection for Whisper:
#   one contract, provider chosen by a settings value, documented here.
#
#   The contract is that callers NEVER see an exception. They get an LLMResult
#   whose ai_generated flag says whether a model actually produced the text, so
#   the fallback can be shown and labelled rather than passed off as AI.
# ───────────────────────────────────────────────────────────────────────────
"""One LLM entry point for the whole product.

Providers, selected via settings.LLM_PROVIDER:
  - "groq"   (default) — OpenAI-compatible, so the same `openai` SDK is used
                         with base_url pointed at Groq. Needs GROQ_API_KEY.
  - "openai"           — the original hosted path. Needs OPENAI_API_KEY.
  - "none"             — never calls out; every request reports NOT_CONFIGURED.
                         Useful for demos and tests.

Nothing here raises. Every outcome is classified, logged with its `purpose`,
and returned.
"""
from __future__ import annotations

import hashlib
import json
import time
from dataclasses import dataclass, field
from typing import Any

import structlog

from app.core.config import settings

logger = structlog.get_logger()

# ── Outcomes ─────────────────────────────────────────────────────────────────
OK = "OK"
CACHED = "CACHED"
NOT_CONFIGURED = "NOT_CONFIGURED"   # no key, or provider is "none"
AUTH_FAILED = "AUTH_FAILED"         # 401 — wrong or revoked key
RATE_LIMITED = "RATE_LIMITED"       # 429 — survived the retries
MODEL_NOT_FOUND = "MODEL_NOT_FOUND"  # 404 — LLM_MODEL is wrong or retired
TIMEOUT = "TIMEOUT"
BAD_RESPONSE = "BAD_RESPONSE"       # answered, but not the JSON we asked for
UPSTREAM_ERROR = "UPSTREAM_ERROR"   # anything else

# Retrying cannot fix a bad key or an unknown model, and retrying a timeout on a
# request a user is waiting for just doubles the wait.
_RETRYABLE = {RATE_LIMITED, UPSTREAM_ERROR}


@dataclass
class LLMResult:
    """What a caller gets back. Never an exception."""
    status: str
    text: str = ""
    data: dict[str, Any] = field(default_factory=dict)
    provider: str = ""
    model: str = ""
    latency_ms: int = 0
    cached: bool = False
    failure_reason: str | None = None

    @property
    def ai_generated(self) -> bool:
        """True only when a model actually produced this. A cached answer still
        counts — it was generated by a model, just not on this request."""
        return self.status in (OK, CACHED)


# ── Provider wiring ──────────────────────────────────────────────────────────
def resolved_provider() -> tuple[str, str, str]:
    """(provider, model, api_key). Provider is "none" when unusable."""
    p = (settings.LLM_PROVIDER or "none").strip().lower()
    if p == "groq":
        return ("groq" if settings.GROQ_API_KEY else "none",
                settings.LLM_MODEL, settings.GROQ_API_KEY)
    if p == "openai":
        return ("openai" if settings.OPENAI_API_KEY else "none",
                settings.LLM_MODEL_OPENAI, settings.OPENAI_API_KEY)
    return ("none", "", "")


def _client(provider: str, api_key: str):
    from openai import OpenAI
    if provider == "groq":
        # Groq speaks the OpenAI wire protocol, so no new dependency is needed —
        # only a different base_url.
        return OpenAI(api_key=api_key, base_url=settings.GROQ_BASE_URL,
                      timeout=settings.LLM_TIMEOUT_SECONDS)
    return OpenAI(api_key=api_key, timeout=settings.LLM_TIMEOUT_SECONDS)


def _classify(exc: Exception) -> str:
    """Map an SDK exception onto one of our statuses.

    Matched on status_code first and class name second, rather than by importing
    the SDK's exception classes, so a minor openai version bump cannot silently
    turn every failure into UPSTREAM_ERROR.
    """
    code = getattr(getattr(exc, "response", None), "status_code", None) or getattr(exc, "status_code", None)
    if code == 400:
        # Groq validates JSON server-side and returns 400 json_validate_failed
        # when a reasoning model runs out of budget mid-object. That is a
        # response-shape problem, not a transient one — retrying it three times
        # only spends the rate limit to fail three ways.
        return BAD_RESPONSE
    if code == 401 or code == 403:
        return AUTH_FAILED
    if code == 404:
        return MODEL_NOT_FOUND
    if code == 429:
        return RATE_LIMITED
    name = type(exc).__name__.lower()
    if "timeout" in name:
        return TIMEOUT
    if "authentication" in name or "permissiondenied" in name:
        return AUTH_FAILED
    if "notfound" in name:
        return MODEL_NOT_FOUND
    if "ratelimit" in name:
        return RATE_LIMITED
    return UPSTREAM_ERROR


# ── Cache + failure counters (Redis, with an in-process fallback) ─────────────
class _MemoryStore:
    """Used when Redis is unreachable, so the seam works with no infrastructure
    — the same approach otp_service takes."""

    def __init__(self) -> None:
        self._d: dict[str, tuple[float, str]] = {}

    def get(self, k: str) -> str | None:
        hit = self._d.get(k)
        if not hit:
            return None
        expires, val = hit
        if expires < time.time():
            self._d.pop(k, None)
            return None
        return val

    def setex(self, k: str, ttl: int, v: str) -> None:
        self._d[k] = (time.time() + ttl, v)

    def incr(self, k: str) -> int:
        cur = int(self.get(k) or 0) + 1
        self.setex(k, 86400, str(cur))
        return cur

    def expire(self, k: str, ttl: int) -> None:  # pragma: no cover - parity only
        pass


_store = None


def _get_store():
    global _store
    if _store is None:
        try:
            import redis
            c = redis.from_url(settings.REDIS_URL, decode_responses=True,
                               socket_connect_timeout=0.5)
            c.ping()
            _store = c
        except Exception:
            _store = _MemoryStore()
    return _store


def reset_store_for_tests() -> None:
    """Tests inject their own store; production never calls this."""
    global _store
    _store = None


def _cache_key(purpose: str, model: str, prompt: str, system: str | None) -> str:
    digest = hashlib.sha256(f"{model}\x00{system or ''}\x00{prompt}".encode()).hexdigest()[:32]
    return f"llm:cache:{purpose}:{digest}"


def _record(purpose: str, status: str) -> None:
    """Rolling per-purpose counters, so "the AI is broken" becomes answerable:
    which feature, and failing how."""
    try:
        store = _get_store()
        key = f"llm:stat:{purpose}:{status}"
        store.incr(key)
        store.expire(key, 86400)
    except Exception:
        pass       # telemetry must never break the request it is measuring


def stats() -> dict[str, dict[str, int]]:
    """Counters by purpose, for GET /manager/ai/health."""
    out: dict[str, dict[str, int]] = {}
    try:
        store = _get_store()
        if isinstance(store, _MemoryStore):
            keys = [k for k in store._d if k.startswith("llm:stat:")]
            getter = store.get
        else:
            keys = list(store.scan_iter("llm:stat:*"))
            getter = store.get
        for k in keys:
            _, _, purpose, status = k.split(":", 3)
            out.setdefault(purpose, {})[status] = int(getter(k) or 0)
    except Exception:
        pass
    return out


# ── The one public call ──────────────────────────────────────────────────────
def complete(
    prompt: str,
    *,
    purpose: str,
    system: str | None = None,
    json_mode: bool = False,
    max_tokens: int = 400,
    temperature: float = 0.3,
    cache_ttl: int | None = None,
) -> LLMResult:
    """Ask the model. Returns an LLMResult; never raises.

    `purpose` is a short stable label for the feature making the call
    ("visit_strategy", "briefing", ...). It keys the logs, the counters and the
    cache, and is what turns a vague "the AI is down" into a specific answer.
    """
    provider, model, api_key = resolved_provider()
    started = time.monotonic()

    if provider == "none":
        _record(purpose, NOT_CONFIGURED)
        logger.warning("llm.not_configured", purpose=purpose,
                       configured_provider=settings.LLM_PROVIDER)
        return LLMResult(status=NOT_CONFIGURED, provider="none",
                         failure_reason="No API key configured for the selected provider")

    ttl = settings.LLM_CACHE_TTL_SECONDS if cache_ttl is None else cache_ttl
    key = _cache_key(purpose, model, prompt, system)
    if ttl > 0:
        try:
            hit = _get_store().get(key)
        except Exception:
            hit = None
        if hit:
            payload = json.loads(hit)
            _record(purpose, CACHED)
            return LLMResult(
                status=CACHED, text=payload.get("text", ""), data=payload.get("data") or {},
                provider=provider, model=model, cached=True,
                latency_ms=int((time.monotonic() - started) * 1000),
            )

    messages: list[dict] = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})

    kwargs: dict[str, Any] = {
        "model": model, "messages": messages,
        "max_tokens": max_tokens, "temperature": temperature,
    }
    if json_mode:
        kwargs["response_format"] = {"type": "json_object"}
    if settings.LLM_REASONING_EFFORT:
        # Not a typed parameter on openai==1.57.4, so it rides in extra_body.
        # A provider that does not recognise it ignores it.
        kwargs["extra_body"] = {"reasoning_effort": settings.LLM_REASONING_EFFORT}

    last_status = UPSTREAM_ERROR
    last_detail: str | None = None

    for attempt in range(settings.LLM_MAX_RETRIES + 1):
        try:
            resp = _client(provider, api_key).chat.completions.create(**kwargs)
            text = (resp.choices[0].message.content or "").strip()
            data: dict[str, Any] = {}
            if json_mode:
                try:
                    parsed = json.loads(text)
                except (ValueError, TypeError) as exc:
                    # The model answered but not in the shape we asked for. A
                    # weaker model drifting on a strict JSON contract lands here,
                    # which is exactly what we want visible rather than swallowed.
                    _record(purpose, BAD_RESPONSE)
                    logger.warning("llm.bad_response", purpose=purpose, provider=provider,
                                   model=model, error=str(exc), preview=text[:120])
                    return LLMResult(status=BAD_RESPONSE, provider=provider, model=model,
                                     text=text, failure_reason="Model did not return valid JSON",
                                     latency_ms=int((time.monotonic() - started) * 1000))
                data = parsed if isinstance(parsed, dict) else {"value": parsed}

            latency = int((time.monotonic() - started) * 1000)
            if ttl > 0:
                try:
                    _get_store().setex(key, ttl, json.dumps({"text": text, "data": data}))
                except Exception:
                    pass
            _record(purpose, OK)
            logger.info("llm.ok", purpose=purpose, provider=provider, model=model,
                        latency_ms=latency, attempt=attempt, cached=False)
            return LLMResult(status=OK, text=text, data=data, provider=provider,
                             model=model, latency_ms=latency)

        except Exception as exc:
            last_status = _classify(exc)
            last_detail = str(exc)[:200]
            retryable = last_status in _RETRYABLE and attempt < settings.LLM_MAX_RETRIES
            logger.warning("llm.failed", purpose=purpose, provider=provider, model=model,
                           status=last_status, attempt=attempt, will_retry=retryable,
                           error=last_detail)
            if not retryable:
                break
            # Honour Retry-After when the provider sends one — Groq does, and
            # ignoring it is how a rate limit becomes a ban.
            wait = _retry_after(exc)
            time.sleep(min(wait if wait is not None else 0.5 * (2 ** attempt), 5.0))

    _record(purpose, last_status)
    return LLMResult(status=last_status, provider=provider, model=model,
                     failure_reason=last_detail,
                     latency_ms=int((time.monotonic() - started) * 1000))


def _retry_after(exc: Exception) -> float | None:
    try:
        headers = getattr(getattr(exc, "response", None), "headers", None) or {}
        raw = headers.get("retry-after") or headers.get("Retry-After")
        return float(raw) if raw is not None else None
    except (TypeError, ValueError):
        return None


def health() -> dict:
    """Provider, model and whether a key is present — for the health endpoint
    and the startup log. Never includes the key itself."""
    provider, model, api_key = resolved_provider()
    return {
        "configured_provider": settings.LLM_PROVIDER,
        "active_provider": provider,
        "model": model or None,
        "key_present": bool(api_key),
        "usable": provider != "none",
        "cache_ttl_seconds": settings.LLM_CACHE_TTL_SECONDS,
        "timeout_seconds": settings.LLM_TIMEOUT_SECONDS,
        "counters": stats(),
    }
